import { build } from 'esbuild';
import { copyFile } from 'node:fs/promises';
await build({ entryPoints: ['scripts/password-crypto.js'], outfile: 'PasswordCrypto.gs', bundle: true, format: 'iife', globalName: 'PasswordCrypto', platform: 'browser', target: 'es2020', minify: false, banner: { js: '// Generated by npm run build:crypto. @noble/hashes 1.8.0, MIT; see THIRD_PARTY_LICENSE.txt.' } });
await copyFile('node_modules/@noble/hashes/LICENSE', 'THIRD_PARTY_LICENSE.txt');
console.log('PasswordCrypto.gs generated.');
